### PR TITLE
Atomic design: Fix buttons

### LINKED ISSUE #177: Atomic Design: Fix changes in buttons

### PR DESCRIPTION
**Pull request by anhelinakruk**
After the meeting with the designer now there are new things to fix in Buttons atom. That's what is done in this PR

- Add disabled variant
- Add height and px to "small" and "large" sizes
- Fix hover

### CODE REVIEW

File: src/components/Atoms/Buttons/Button.tsx [hunk 1]
```diff
@@ -43,18 +42,36 @@ export type buttonType = VariantProps<typeof buttonStyles> & ButtonProps;
 
 const Button = ({ variant, size, ...props }: buttonType) => {
```
Comment (pgajek) [inline src/components/Atoms/Buttons/Button.tsx]: Uzyj prosze "component$"

**Review by pgajek — CHANGES_REQUESTED** [review]

File: src/components/Atoms/Buttons/Button.tsx (hunk 1 above)
Comment (anhelinakruk) [reply src/components/Atoms/Buttons/Button.tsx]: Zrobione

**Review by pgajek — APPROVED** [review]
